services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8096:8096"
    volumes:
      - ./data/sqlite:/app/sqlite

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=https://api.prij.zim.is
    depends_on:
      - backend