version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Backend/Dockerfile
    ports:
      - "8096:8096"

  frontend:
    build:
      context: .
      dockerfile: Frontend/Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8096
    depends_on:
      - backend